export const ACTION_TYPES = {
  SEND_NEWSLETTER_START: 'NEWSLETTER/SEND_NEWSLETTER_START',
  SEND_NEWSLETTER_SUCCESS: 'NEWSLETTER/SEND_NEWSLETTER_SUCCESS',
  SEND_NEWSLETTER_FAIL: 'NEWSLETTER/SEND_NEWSLETTER_FAIL',
  CLEAR_STATE: 'NEWSLETTER/CLEAR_STATE'
};
