export const ACTION_TYPES = {
  CREATE_STORE_START: 'CREATE_STORE/CREATE_STORE_START',
  CREATE_STORE_SUCCESS: 'CREATE_STORE/CREATE_STORE_SUCCESS',
  CREATE_STORE_FAIL: 'CREATE_STORE/CREATE_STORE_FAIL',
  CLEAR_STATE: 'CREATE_STORE/CLEAR_STATE'
};
