export const ACTION_TYPES = {
  UPDATE_STORE_START: 'UPDATE_STORE/UPDATE_STORE_START',
  UPDATE_STORE_SUCCESS: 'UPDATE_STORE/UPDATE_STORE_SUCCESS',
  UPDATE_STORE_FAIL: 'UPDATE_STORE/UPDATE_STORE_FAIL',
  CLEAR_STATE: 'UPDATE_STORE/CLEAR_STATE'
};
