export const ACTION_TYPES = {
  UPDATE_COUPON_START: 'UPDATE_COUPON/UPDATE_COUPON_START',
  UPDATE_COUPON_SUCCESS: 'UPDATE_COUPON/UPDATE_COUPON_SUCCESS',
  UPDATE_COUPON_FAIL: 'UPDATE_COUPON/UPDATE_COUPON_FAIL',
  CLEAR_STATE: 'UPDATE_COUPON/CLEAR_STATE'
};
