export const ACTION_TYPES = {
  FETCH_PAGINATED_COUPONS_START: 'COUPONS/FETCH_PAGINATED_COUPONS_START',
  FETCH_PAGINATED_COUPONS_SUCCESS: 'COUPONS/FETCH_PAGINATED_COUPONS_SUCCESS',
  FETCH_PAGINATED_COUPONS_FAIL: 'COUPONS/FETCH_PAGINATED_COUPONS_FAIL'
};
