export const ACTION_TYPES = {
  UPDATE_QUERY: 'SEARCHED_COUPONS/UPDATE_QUERY',
  LOAD_DATA_START: 'SEARCHED_COUPONS/LOAD_DATA_START',
  LOAD_DATA_SUCCESS: 'SEARCHED_COUPONS/LOAD_DATA_SUCCESS',
  LOAD_DATA_FAIL: 'SEARCHED_COUPONS/LOAD_DATA_FAIL'
};
