export const ACTION_TYPES = {
  LOAD_DATA_START: 'FEATURED_COUPONS/LOAD_DATA_START',

  LOAD_DATA_SUCCESS: 'FEATURED_COUPONS/LOAD_DATA_SUCCESS',

  LOAD_DATA_FAIL: 'FEATURED_COUPONS/LOAD_DATA_FAIL'
};
