export const ACTION_TYPES = {
  CHANGE_MODAL_STATE: 'NEWSLETTER/CHANGE_MODAL_STATE',
  SUBSCRIBE_START: 'NEWSLETTER/SUBSCRIBE_START',
  SUBSCRIBE_SUCCESS: 'NEWSLETTER/SUBSCRIBE_SUCCESS',
  SUBSCRIBE_FAIL: 'NEWSLETTER/SUBSCRIBE_FAIL'
};
