export const ACTION_TYPES = {
  LOGIN_START: 'USER/LOGIN_START',
  LOGIN_SUCCESS: 'USER/LOGIN_SUCCESS',
  LOGIN_FAIL: 'USER/LOGIN_FAIL',
  LOGOUT_START: 'USER/LOGOUT_START',
  LOGOUT_SUCCESS: 'USER/LOGOUT_SUCCESS',
  LOGOUT_FAIL: 'USER/LOGOUT_FAIL'
};
