export const ACTION_TYPES = {
  DELETE_STORE_START: 'DELETE_STORE/DELETE_STORE_START',
  DELETE_STORE_SUCCESS: 'DELETE_STORE/DELETE_STORE_SUCCESS',
  DELETE_STORE_FAIL: 'DELETE_STORE/DELETE_STORE_FAIL',
  CLEAR_STATE: 'DELETE_STORE/CLEAR_STATE'
};
