export const ACTION_TYPES = {
  LOAD_DATA_START: 'PAGINATED_STORES/LOAD_DATA_START',

  LOAD_DATA_SUCCESS: 'PAGINATED_STORES/LOAD_DATA_SUCCESS',

  LOAD_DATA_FAIL: 'PAGINATED_STORES/LOAD_DATA_FAIL'
};
