export const ACTION_TYPES = {
  DELETE_COUPON_START: 'DELETE_COUPON/DELETE_COUPON_START',
  DELETE_COUPON_SUCCESS: 'DELETE_COUPON/DELETE_COUPON_SUCCESS',
  DELETE_COUPON_FAIL: 'DELETE_COUPON/DELETE_COUPON_FAIL',
  CLEAR_STATE: 'DELETE_COUPON/CLEAR_STATE'
};
