export const ACTION_TYPES = {
  CREATE_COUPON_START: 'CREATE_COUPON/CREATE_COUPON_START',
  CREATE_COUPON_SUCCESS: 'CREATE_COUPON/CREATE_COUPON_SUCCESS',
  CREATE_COUPON_FAIL: 'CREATE_COUPON/CREATE_COUPON_FAIL',
  CLEAR_STATE: 'CREATE_COUPON/CLEAR_STATE'
};
