export const ACTION_TYPES = {
  FETCH_STORES_START: 'STORES/FETCH_STORES_START',
  FETCH_STORES_SUCCESS: 'STORES/FETCH_STORES_SUCCESS',
  FETCH_STORES_FAIL: 'STORES/FETCH_STORES_FAIL',
  FETCH_PAGINATED_STORES_START: 'STORES/FETCH_PAGINATED_STORES_START',
  FETCH_PAGINATED_STORES_SUCCESS: 'STORES/FETCH_PAGINATED_STORES_SUCCESS',
  FETCH_PAGINATED_STORES_FAIL: 'STORES/FETCH_PAGINATED_STORES_FAIL'
};
